name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "checkRepo"
        uses: actions/checkout@v2
      
      - name: "create_output_dir"
        run: mkdir output

      - name: "convert readme.md to index.html"
        uses: docker://shameoff/pandoc-latex-dejavu
        with:
          args: >-
            README.md
            --output=output/index.html
            --template=resources/template.html

      - name: "make temp.html from readme.md"
        uses: docker://shameoff/pandoc-latex-dejavu
        with:
          args: >-
            README.md
            --output=temp.html
        
      - name: "convert temp.html to pdf"
        uses: docker://shameoff/pandoc-latex-dejavu
        with:
          args: >-
            temp.html
            --output=output/cv.pdf
            --pdf-engine=xelatex
            --listings
            --css=resources/css/bootstrap.min.css
            -V geometry:"left=1.5cm,right=1.5cm,top=2cm,bottom=2cm"
            -V colorlinks=trgue
            -V linkcolor=blue
            -V urlcolor=blue
            -V toccolor=gray
            -V mainfont="DejaVuSans"

      - name: "upload artifacts to download them later"
        uses: actions/upload-artifact@v3
        with:
          name: "converted"
          path: "output/"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "pull dependencies on host with ssh"
        uses: appleboy/ssh-action@v0.1.10
        with:
          username: ${{ secrets.REMOTE_USER }} 
          key: ${{ secrets.ACTOR_PRIVATE_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          script: "cd /projects/my_CV && git pull"
      
      - name: "download artifacts from build"
        uses: actions/download-artifact@v2
        with:
          name: "converted"
          path: "build/"

      - name: "copy artifacts to server"
        uses: appleboy/scp-action@v0.1.4
        with:
          username: ${{ secrets.REMOTE_USER }} 
          key: ${{ secrets.ACTOR_PRIVATE_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          source: "build/*"
          target: "/projects/my_CV/"
          strip_components: 1 # для того, чтобы папки build не существовало
      
