name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkRepo
        uses: actions/checkout@v2
      
      - name: create_output_dir
        run: mkdir output


      - name: convert_with_pandoc
        uses: docker://pandoc/latex:2.9
        with:
          args: >-
            --output=output/index.html
            --template=template.html
            README.md

      - name: create temp.html
        uses: docker://pandoc/latex:2.9
        with:
          args: >-
            README.md
            --output=temp.html
        
      - name: install fonts
        run: sudo apt update && sudo apt install fonts-dejavu-core fonts-dejavu-extra
      
      - name: convert temp.html to pdf
        uses: docker://pandoc/latex:2.9
        with:
          args: >-
            temp.html
            --output=output/cv.pdf
            --pdf-engine=xelatex
            --listings
            --css=css/bootstrap.min.css
            -V geometry:"left=1.5cm,right=1.5cm,top=2cm,bottom=2cm"
            -V colorlinks=trgue
            -V linkcolor=blue
            -V urlcolor=blue
            -V toccolor=gray
            -V mainfont="DejaVu Sans"

      - name: upload artifacts to download them later
        uses: actions/upload-artifact@v3
        with:
          name: converted-files
          path: output/

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push files to remote host
        run: scp -P ${{secrets.REMOTE_PORT}} output/ ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}}:/projects/my_CV
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.ACTOR_PRIVATE_KEY }}
      
      - name: Delivery with ssh-key
        uses: "appleboy/ssh-action@v0.1.10"
        with:
          username: ${{ secrets.REMOTE_USER }} 
          key: ${{ secrets.ACTOR_PRIVATE_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          script: cd /projects/my_CV && git pull 

